### ISSUE TITLE
Creating gcore_k8sv2 is broken 

### ISSUE THREAD

**Issue by zadjadr** [G-Core/terraform-provider-gcore#84]
Version 0.4.2

Error message:

```
gcore_k8sv2.cluster: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with gcore_k8sv2.cluster,
│   on k8s.tf line 2, in resource "gcore_k8sv2" "cluster":
│    2: resource "gcore_k8sv2" "cluster" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange
│ call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-gcore_v0.4.2 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 81 [running]:
github.com/terraform-providers/terraform-provider-gcore/gcore.resourceK8sV2Create({0x123f560, 0xc000335340}, 0x0?, {0xeb9ac0?, 0xc000669ad0?})
        github.com/terraform-providers/terraform-provider-gcore/gcore/resource_gcore_k8sv2.go:340 +0x1a2f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0005b8460, {0x123f4b8, 0xc00067eae0}, 0xd?, {0xeb9ac0, 0xc000669ad0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:733 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0005b8460, {0x123f4b8, 0xc00067eae0}, 0xc000485380, 0xc0008c8080, {0xeb9ac0, 0xc000669ad0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003bfe90, {0x123f4b8?, 0xc00067e9f0?}, 0xc0004a7950)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00070e460, {0x123f4b8?, 0xc00067e000?}, 0xc000334850)
        github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov5/tf5server/server.go:821 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x104b5e0?, 0xc00070e460}, {0x123f4b8, 0xc00067e000}, 0xc0003347e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003e4000, {0x1243d20, 0xc00051c1a0}, 0xc00066efc0, 0xc00070ccf0, 0x19b6880, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1337 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0003e4000, {0x1243d20, 0xc00051c1a0}, 0xc00066efc0, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1714 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.1/server.go:959 +0x8d
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 52
        google.golang.org/grpc@v1.56.1/server.go:957 +0x165

Error: The terraform-provider-gcore_v0.4.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Cluster I wanted to create: 

```hcl
// public cluster with private dual-stack interface, ipv6 addresses is accessible
resource "gcore_k8sv2" "cluster" {
  project_id = data.gcore_project.project.id
  region_id  = var.gcore_region_id
  version    = var.k8s_version

  name = var.k8s_name

  fixed_network      = gcore_network.k8s_network.id
  fixed_subnet       = gcore_subnet.k8s_subnet_v4.id
  pods_ipv6_pool     = var.k8s_pods_ipv6_pool
  services_ipv6_pool = var.k8s_services_ipv6_pool

  keypair = gcore_keypair.k8s_ssh_keypair.id

  is_ipv6 = true

  cni {
    provider = "calico"
  }

  pool {
    name                 = "g2-2-8g"
    flavor_id            = "g2-standard-2-8"
    min_node_count       = 1
    max_node_count       = 1
    boot_volume_size     = 50
    boot_volume_type     = "standard"
    is_public_ipv4       = true
    auto_healing_enabled = true
  }

  depends_on = [
    gcore_subnet.k8s_subnet_v6,
    gcore_subnet.k8s_subnet_v4,
  ]
}
```

**Comment by alexk53** [comment]
pls try new version - `v0.4.3`
and also we add required param to the poll section - `server group_policy` there are three values `anti-affinity`, `soft-anti-affinity` or `affinity`.

**Affinity rule**:
Boost performance by grouping related nodes together. They will be hosted on the same physical server for faster interaction, enhancing communication and resource sharing.

**Anti-affinity soft rule**:
Balance separation and flexibility, occasionally placing nodes on different servers  physical servers for fault tolerance, or on the same physical server for faster interaction and resource optimization.

**Anti-affinity hard rule**:
Strictly isolate nodes to different physical servers, minimizing simultaneous failures for critical applications. Choose this for enhanced fault tolerance.

**Comment by zadjadr** [comment]
Thanks it works now, but the cluster is completely broken. No pod is scheduled and many other issues.. I've created a ticket: https://support.gcore.com/hc/en-us/requests/714988

**Comment by zadjadr** [comment]
Since the underlying problem of this issue has been fixed, I'll close the issue.
